version: '3' 

services:

  front:
    build:
        context: ./docker-config/react
        dockerfile: Dockerfile
    container_name: react
    volumes: 
      - ./:/var/www
    working_dir: /var/www
    command: node
    tty: true
    ports:
      - "3000:3000"

  web: 
    build: ./docker-config/php
    container_name: app_php
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: app_nginx
    build: ./docker-config/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    container_name: app_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cocospace
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: m_user
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions